Daniel/1.logparser
Les-Mobiles/Bee pull request #8
Opened 2020-11-02 04:54 UTC by afterxleep

#1 

- BuildParser Protocol
- BuildParser implementation by running xclogparses via shell
- Parse latest log for specific project, given an specific DerivedData folder
- Return a codable Object with the summary report.
- Unit tests for common scenarios

2020-11-02 19:49 UTC, sanarroya requested changes

2020-11-02 19:49 UTC, sanarroya commented on Bee/ParserTestView.swift
> +struct ParserTestView: View {
Is this only used for testing purposes? if so, I think we should move it to a different folder maybe `BeeUITests`would be more appropriate

2020-11-02 19:49 UTC, sanarroya commented on Bee/ParserTestView.swift
> +    private func promptForWorkingDirectoryPermission() -> URL? {
What do you think about grouping `private methods` inside a `private extension`?

2020-11-02 19:49 UTC, sanarroya commented on Bee/Services/BuildParser/BuildParser.swift
>  enum LogParserError: Error {
Should we make this conform to `LocalizedError` and add an error description for each one?

2020-11-02 19:49 UTC, sanarroya commented on Bee/Services/BuildParser/BuildParser.swift
> +                   withData derivedData: String) -> Result<BuildSummary?, LogParserError>
Why is `BuildSummary` optional, I guess if it happens to be nil then there was an error parsing and the result should be a failure, what do you think?

2020-11-02 19:49 UTC, sanarroya commented on Bee/Services/BuildParser/BuildParserXCLog.swift
> +    private let shell = "/bin/bash"
Please move this constants to an enum

2020-11-02 19:49 UTC, sanarroya commented on Bee/Services/BuildParser/BuildParserXCLog.swift
> +        let parsedData = outputPipe.fileHandleForReading.readDataToEndOfFile()
Is this running in the main thread? should it be moved to a different one?

2020-11-02 19:49 UTC, sanarroya commented on Bee/Services/BuildParser/BuildParserXCLog.swift
> +        if(!error.isEmpty) {
Please remove parentheses

2020-11-02 19:49 UTC, sanarroya commented on Bee/Services/BuildParser/BuildParserXCLog.swift
> +            let e = String(data: error, encoding: .utf8)
Could we use a more descriptive name for this variable?

2020-11-02 19:49 UTC, sanarroya commented on Bee/Services/BuildParser/BuildParserXCLog.swift
> +            if((e?.contains(unrecognizedArgs)) != nil) {
Please remove parentheses

2020-11-02 19:49 UTC, sanarroya commented on Bee/Services/BuildParser/BuildParserXCLog.swift
> +        if((e?.contains(projectNotFound)) != nil) {
Please remove parentheses

2020-11-02 19:49 UTC, sanarroya commented on Bee/Services/BuildParser/BuildParserXCLog.swift
> +        let e = String(data: data, encoding: .utf8)
Could we use a more descriptive name for this variable?

2020-11-02 19:49 UTC, sanarroya commented on Bee/Services/BuildParser/BuildParserXCLog.swift
> +                    return .failure(handleXCLogParserError(data))
I'm curious about this, why are you calling `handleXCLogParserError(data)` which only returns two types of errors instead of sending the thrown error?

2020-11-02 19:49 UTC, sanarroya commented on BeeTests/BeeTests-Bridging-Header.h
> +//
Do we need this file?

2020-11-02 19:49 UTC, sanarroya commented on BeeTests/BuildParserXCLogTests.swift
> +    private let derivedDataPath = "/Library/Developer/Xcode/DerivedData/"
Please move this to a constants enum

2020-11-02 19:49 UTC, sanarroya commented on BeeTests/BuildParserXCLogTests.swift
> +    override func setUpWithError() throws {
Please remove this empty method

2020-11-02 19:49 UTC, sanarroya commented on BeeTests/BuildParserXCLogTests.swift
> +    override func tearDownWithError() throws {
ditto

2020-11-02 19:49 UTC, sanarroya commented on BeeTests/BuildParserXCLogTests.swift
> +        var duration: Float = 0
Do we need to specify the type here?

2020-11-02 19:49 UTC, sanarroya commented on BeeTests/BuildParserXCLogTests.swift
> +            default: break
You can call `XCTFail()`to fail the test if it happens to go this path

2020-11-02 19:49 UTC, sanarroya commented on BeeTests/BuildParserXCLogTests.swift
> +                break
You can call `XCTFail()`to fail the test if it happens to go this path

2020-11-02 20:11 UTC, afterxleep commented on Bee/ParserTestView.swift
> +struct ParserTestView: View {
I'll pull the file off the repo.  This was a test I did just to understand how the FIlePicker works.

2020-11-02 20:11 UTC, afterxleep commented on Bee/ParserTestView.swift
> +    private func promptForWorkingDirectoryPermission() -> URL? {
yea, ignore this file..

2020-11-02 20:13 UTC, afterxleep commented on Bee/Services/BuildParser/BuildParser.swift
> +                   withData derivedData: String) -> Result<BuildSummary?, LogParserError>
Since this is a third party script running on shell, detecting errors is hard as we need to parse text output, so we might not catch everything.  Allowing nil for now is better suited, at lease until we can use the library directly from the project.

2020-11-02 20:14 UTC, afterxleep commented on BeeTests/BuildParserXCLogTests.swift
> +        var duration: Float = 0
With type inference the compiler gets confused with a Double for some reason...   Will double check,.

2020-11-02 20:14 UTC, afterxleep commented on BeeTests/BuildParserXCLogTests.swift
> +            default: break
good catch

2020-11-02 20:15 UTC, afterxleep commented on BeeTests/BuildParserXCLogTests.swift
> +                break
ditto.

2020-11-03 01:18 UTC, sanarroya approved these changes

2020-11-03 05:13 UTC, afterxleep commented on Bee/Services/BuildParser/BuildParserXCLog.swift
> +        let parsedData = outputPipe.fileHandleForReading.readDataToEndOfFile()
hum..  I'd say is not running in the main thread if you Dispatch the Parser class.   Don't think we need to take care of threading here, but when we call the parser..

2020-11-03 05:16 UTC, afterxleep commented on Bee/Services/BuildParser/BuildParserXCLog.swift
> +                    return .failure(handleXCLogParserError(data))
Scalability.  Rigth now there are just 2 but that's the bare minimum..  We still don't know of other errors the parser may throw...

2020-11-03 05:18 UTC, afterxleep commented on BeeTests/BeeTests-Bridging-Header.h
> +//
Good catch.  Damn Xcoded added it..

2020-11-03 05:20 UTC, merged